version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: faker
    versions:
    - 5.6.5
    - 5.8.0
    - 6.0.0
    - 6.1.1
    - 6.4.1
    - 6.5.0
    - 6.6.0
    - 6.6.2
    - 6.6.3
    - 7.0.1
    - 8.0.0
    - 8.1.0
  - dependency-name: flake8-bugbear
    versions:
    - 20.11.1
    - 21.3.1
    - 21.3.2
  - dependency-name: coverage
    versions:
    - 5.3.1
    - "5.4"
  - dependency-name: pytest
    versions:
    - 6.2.1
    - 6.2.2
  - dependency-name: flake8-comprehensions
    versions:
    - 3.3.1
